/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.exercicio2.view;

import br.edu.map.exercicio2.dao.ProdutoDAO;
import br.edu.map.exercicio2.model.Produto;
import br.edu.map.exercicio2.util.MensagensUtil;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class ProdutoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    private ProdutoDAO dao;
    private ProdutosJFrame principal;
    
    public ProdutoJFrame(ProdutosJFrame parent) {
        this.principal = parent;
        this.dao = new ProdutoDAO();
        this.setLocation(400, 200);
        initComponents();
        preencherDados();
    }
    
    private void preencherDados(){
        Produto selecionado = principal.getProduto_selecionado();
        
        if(selecionado == null){
            labelProduto.setText(MensagensUtil.getString(MensagensUtil.MSG_TITLE_PRODUTO_NOVO));
        }else{
            labelProduto.setText(MensagensUtil.getString(MensagensUtil.MSG_TITLE_PRODUTO_EDITAR));
            textNome.setText(selecionado.getNome());
            textPreco.setText(String.valueOf(selecionado.getPreco()));
            textFabricante.setText(selecionado.getEsp().getFabricante());
            textCor.setText(selecionado.getEsp().getCor());
            textSistema.setText(selecionado.getEsp().getSistema());
            textDetalhe.setText(selecionado.getEsp().getDetalhe());
       }
       this.labelNome.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_NOME));
       this.labelPreco.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_PRECO));
       this.labelFabricante.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_FABRICANTE));
       this.labelCor.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_COR));
       this.labelSistema.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_SISTEMA));
       this.labelDetalhe.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_DETALHE));
       this.buttonSalvar.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_SALVAR));
       this.buttonCancelar.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_CANCELAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProduto = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        textPreco = new javax.swing.JTextField();
        labelFabricante = new javax.swing.JLabel();
        textFabricante = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        textCor = new javax.swing.JTextField();
        labelSistema = new javax.swing.JLabel();
        textSistema = new javax.swing.JTextField();
        labelDetalhe = new javax.swing.JLabel();
        textDetalhe = new javax.swing.JTextField();
        buttonCancelar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProduto.setText("PRODUTO");

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelNome.setText("Nome:");

        textNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        labelPreco.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelPreco.setText("Preço:");

        textPreco.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        labelFabricante.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelFabricante.setText("Fabricante:");

        textFabricante.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        labelCor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelCor.setText("Cor:");

        textCor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        labelSistema.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelSistema.setText("Sistema:");

        textSistema.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        labelDetalhe.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelDetalhe.setText("Detalhe:");

        textDetalhe.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        buttonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonSalvar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNome)
                    .addComponent(textPreco)
                    .addComponent(textFabricante)
                    .addComponent(textCor)
                    .addComponent(textSistema)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelPreco)
                            .addComponent(labelFabricante)
                            .addComponent(labelCor)
                            .addComponent(labelSistema)
                            .addComponent(labelDetalhe))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textDetalhe)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 320, Short.MAX_VALUE)
                        .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDetalhe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // TODO add your handling code here:
        Produto p = principal.getProduto_selecionado();
        
        if(p == null){
            p = new Produto();
            String nome = textNome.getText();
            float preco = Float.parseFloat(textPreco.getText());
            String fabricante = textFabricante.getText();
            String cor = textCor.getText();
            String sistema = textSistema.getText();
            String detalhe = textDetalhe.getText();

            p.setNome(nome);
            p.setPreco(preco);
            p.getEsp().setFabricante(fabricante);
            p.getEsp().setCor(cor);
            p.getEsp().setSistema(sistema);
            p.getEsp().setDetalhe(detalhe);

            try {
                dao.inserir(p);
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, MensagensUtil.getString(MensagensUtil.getString(MensagensUtil.MSG_ERRO)), 
                        MensagensUtil.getString(MensagensUtil.getString(MensagensUtil.MSG_ERRO_INSERIR)),JOptionPane.ERROR_MESSAGE);
            }
        }else{
            p.setNome(textNome.getText());
            p.setPreco(Float.parseFloat(textPreco.getText()));
            p.getEsp().setFabricante(textFabricante.getText());
            p.getEsp().setCor(textCor.getText());
            p.getEsp().setSistema(textSistema.getText());
            p.getEsp().setDetalhe(textDetalhe.getText());
            
            try {
                dao.editar(p);
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, MensagensUtil.getString(MensagensUtil.MSG_ERRO), 
                        MensagensUtil.getString(MensagensUtil.MSG_ERRO_EDITAR), JOptionPane.ERROR_MESSAGE);
            }           
        }
        principal.preencherTabela(null);
        dispose();
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelDetalhe;
    private javax.swing.JLabel labelFabricante;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelSistema;
    private javax.swing.JTextField textCor;
    private javax.swing.JTextField textDetalhe;
    private javax.swing.JTextField textFabricante;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textPreco;
    private javax.swing.JTextField textSistema;
    // End of variables declaration//GEN-END:variables
}
