/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.map.exercicio2.view;

import br.edu.map.exercicio2.dao.ProdutoDAO;
import br.edu.map.exercicio2.model.Produto;
import br.edu.map.exercicio2.util.MensagensUtil;
import br.edu.map.exercicio2.util.RelatorioManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author diego
 */
public class ProdutosJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProdutosJFrame
     */
    
    private ProdutoDAO dao;
    private Produto produto_selecionado;
    
    
    public ProdutosJFrame() {
        dao = new ProdutoDAO();
        this.setTitle("Produtos");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocation(400, 200);
        initComponents();
        preencherTabela(null);
        this.setProperties();
    }
    
    private void setProperties(){
        menuIdioma.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_IDIOMA));
        menuItemptBR.setText(MensagensUtil.getString(MensagensUtil.MSG_MENUITEM_PORTUGUES));
        menuItemenUS.setText(MensagensUtil.getString(MensagensUtil.MSG_MENUITEM_INGLES));
        menuItemesES.setText(MensagensUtil.getString(MensagensUtil.MSG_MENUITEM_ESPANHOL));
        menuRelatorio.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_RELATORIO));
        menuItemListaProdutos.setText(MensagensUtil.getString(MensagensUtil.MSG_MENUITEM_LISTA_PRODUTO));
        menuItemLPPreco.setText(MensagensUtil.getString(MensagensUtil.MSG_MENUITEM_LISTA_PRODUTO_PRECO));
        labelProdutos.setText(MensagensUtil.getString(MensagensUtil.MSG_TITLE_PRODUTOS));
        buttonNovo.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_NOVO));
        buttonEditar.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_EDITAR));
        buttonExcluir.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_EXCLUIR));
        buttonSair.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_SAIR));
        preencherTabela(null);
    }

    public Produto getProduto_selecionado() {
        return produto_selecionado;
    }

    public void setProduto_selecionado(Produto produto_selecionado) {
        this.produto_selecionado = produto_selecionado;
    }
    
    public void preencherTabela(List<Produto> pai){
        try{
            
            List<Produto> lista = (pai == null) ? dao.exibir() : pai;
            
            DefaultTableModel model = new DefaultTableModel();
            
            model.setColumnCount(7);
            model.setColumnIdentifiers(new String[]{
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_CODIGO), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_NOME), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_PRECO), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_FABRICANTE), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_COR), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_SISTEMA), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_DETALHE)});
            model.setRowCount(lista.size());
            
            for(int i = 0; i < lista.size(); i++){
                model.setValueAt(lista.get(i).getCodigo(), i, 0);
                model.setValueAt(lista.get(i).getNome(), i, 1);
                model.setValueAt(lista.get(i).getPreco(), i, 2);
                model.setValueAt(lista.get(i).getEsp().getFabricante(), i, 3);
                model.setValueAt(lista.get(i).getEsp().getCor(), i, 4);
                model.setValueAt(lista.get(i).getEsp().getSistema(), i, 5);
                model.setValueAt(lista.get(i).getEsp().getDetalhe(), i, 6);
            }
            
            tableProdutos.setModel(model);
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelProdutos = new javax.swing.JLabel();
        textFieldBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIdioma = new javax.swing.JMenu();
        menuItemptBR = new javax.swing.JMenuItem();
        menuItemenUS = new javax.swing.JMenuItem();
        menuItemesES = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuItemListaProdutos = new javax.swing.JMenuItem();
        menuItemLPPreco = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProdutos.setText("PRODUTOS");
        labelProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldBuscarKeyReleased(evt);
            }
        });

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProdutos);

        buttonNovo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonNovo.setText("NOVO");
        buttonNovo.setBorder(null);
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonEditar.setText("EDITAR");
        buttonEditar.setBorder(null);
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonExcluir.setText("EXCLUIR");
        buttonExcluir.setBorder(null);
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonSair.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonSair.setText("SAIR");
        buttonSair.setBorder(null);
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        menuIdioma.setText("Idioma");

        menuItemptBR.setText("Português");
        menuItemptBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemptBRActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemptBR);

        menuItemenUS.setText("Inglês");
        menuItemenUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemenUSActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemenUS);

        menuItemesES.setText("Espanhol");
        menuItemesES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemesESActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemesES);

        jMenuBar1.add(menuIdioma);

        menuRelatorio.setText("Relatórios");

        menuItemListaProdutos.setText("Listar Produtos");
        menuItemListaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaProdutosActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuItemListaProdutos);

        menuItemLPPreco.setText("Menos de R$ 1000");
        menuItemLPPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLPPrecoActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuItemLPPreco);

        jMenuBar1.add(menuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProdutos)
                .addGap(18, 18, 18)
                .addComponent(textFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
        if(produto_selecionado != null){
            try{
                
                int op = JOptionPane.showConfirmDialog(this, MensagensUtil.getString(MensagensUtil.MSG_ERRO_EXCLUIR)+ " " + 
                        produto_selecionado.getNome(), MensagensUtil.getString(MensagensUtil.MSG_BUTTON_EXCLUIR), JOptionPane.OK_CANCEL_OPTION);
                if(op == JOptionPane.OK_OPTION){
                    dao.remover(produto_selecionado);
                    preencherTabela(null);
                    produto_selecionado = null;
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this, MensagensUtil.getString(MensagensUtil.MSG_ERRO_SELECIONAR));
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        // TODO add your handling code here:
        produto_selecionado = null;
        ProdutoJFrame janela = new ProdutoJFrame(this);
        janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janela.setVisible(true);
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void textFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldBuscarKeyReleased
        // TODO add your handling code here:
        String busca = textFieldBuscar.getText();
        
        try {
            List<Produto> resultado = dao.buscar(busca);
            preencherTabela(resultado);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_textFieldBuscarKeyReleased

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // TODO add your handling code here:
        if(produto_selecionado != null){
            ProdutoJFrame janela = new ProdutoJFrame(this);
            janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            janela.setVisible(true);    
        }else{
            JOptionPane.showMessageDialog(this, MensagensUtil.getString(MensagensUtil.MSG_ERRO_SELECIONAR));
        }
        
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        // TODO add your handling code here:
        int linha = tableProdutos.rowAtPoint(evt.getPoint());

        int codigo = (int) tableProdutos.getModel().getValueAt(linha, 0);
        
        
        try {
            produto_selecionado = dao.buscar(codigo);
            System.out.println(produto_selecionado);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void menuItemptBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemptBRActionPerformed
        // TODO add your handling code here:
        MensagensUtil.setLocale(MensagensUtil.LOCALE_PT_BR);
        setProperties();
    }//GEN-LAST:event_menuItemptBRActionPerformed

    private void menuItemesESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemesESActionPerformed
        // TODO add your handling code here:
        MensagensUtil.setLocale(MensagensUtil.LOCALE_ES_ES);
        setProperties();
    }//GEN-LAST:event_menuItemesESActionPerformed

    private void menuItemenUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemenUSActionPerformed
        // TODO add your handling code here:
        MensagensUtil.setLocale(MensagensUtil.LOCALE_EN_US);
        setProperties();
    }//GEN-LAST:event_menuItemenUSActionPerformed

    private void menuItemListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaProdutosActionPerformed
        try {
            // TODO add your handling code here:
            JasperPrint relatorio = RelatorioManager.gerarRelatorioProduto(dao.exibir());
            JFrame frame = new JFrame();
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            JRViewer viewer = new JRViewer(relatorio);
            frame.add(viewer);
            frame.setVisible(true);
            
        }   catch (Exception ex) {
            Logger.getLogger(ProdutosJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListaProdutosActionPerformed

    private void menuItemLPPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLPPrecoActionPerformed
        // TODO add your handling code here:
        try{
            JasperPrint relatorio = RelatorioManager.gerarRelatorioProdutoPreco(dao.listarPreco());
            JFrame frame = new JFrame();
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            JRViewer viewer = new JRViewer(relatorio);
            frame.add(viewer);
            frame.setVisible(true);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuItemLPPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosJFrame().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelProdutos;
    private javax.swing.JMenu menuIdioma;
    private javax.swing.JMenuItem menuItemLPPreco;
    private javax.swing.JMenuItem menuItemListaProdutos;
    private javax.swing.JMenuItem menuItemenUS;
    private javax.swing.JMenuItem menuItemesES;
    private javax.swing.JMenuItem menuItemptBR;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField textFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
